apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octai.fullname" . }}
  labels:
    {{- include "octai.labels" . | nindent 4 }}
    {{- include "octai.customDatadogLabels" . | nindent 4 }}
  annotations:
    {{- include "octai.customAnnotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "octai.selectorLabels" . | nindent 6 }}
      gruntwork.io/deployment-type: main
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "octai.selectorLabels" . | nindent 8 }}
        {{- include "octai.customDatadogLabels" . | nindent 8 }}
        gruntwork.io/deployment-type: main
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 15
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 15
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 120
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 15
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 120
            successThreshold: 1
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- with .Values.lifecycle}}
          lifecycle:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
