{{- if .Values.ingress.enabled -}}
{{- $fullName := include "octai.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcName := .Values.service.name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "octai.labels" . | nindent 4 }}
    gruntwork.io/app-name: {{ include "octai.name" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $svcName }}
          {{- end }}
    {{- end }}
{{- end }}
